export const servicesData =[
    {
        id:'1',
        title: 'Rəqəmsal Marketinq',
        info: 'Augue pharetra sem ullamcorper nisl ante. Ac arcu donec sed nunc pharetra nunc vitae. Volutpat arcu augue ut quisque id ut. A et viverra at nunc nisl. Ac a amet ullamcorper nulla etiam suspendisse. Montes tincidunt adipiscing commodo porttitor sit quis dolor velit quam.Commodo mauris semper mauris vitae mauris ultrices. Risus velit aliquet ultrices phasellus id. Duis ut magna rutrum purus ridiculus. Sed condimentum leo.At ac aliquam morbi nullam lorem neque dignissim egestas.',
        name_1: 'Korporativ sayt',
        content_1: 'Korporativ sayt - Sizin şirkətin internetdə olan təmsilçisidir. Doğru şəkildə hazırlanmış korporativ sayt şirkətin üstünlüklərini, müsbət imicini və gücünü özündə əks etdirə bilər.',
        name_2: 'Landing Page Dizaynı',
        content_2: 'Düzgün şəkildə qurulmuş bir səhifəlik landing page hər hansı bir məhsul və ya xidmətinizin satışına necə müsbət təsir etməsini təsəvvür edin.',
        name_3: 'Adaptiv Dizayn',
        content_3: 'Dünyada internet istifadəçilərinin 95% saytlara mobil telefon vasitəsilə daxil olduğunu nəzərə alaraq, təmsil etdiyiniz şirkətin saytının adaptiv olması mütləqdir.',
    },

    {
        id:'2',
        title: 'İstifadəçi təcrübəsi',
        info: 'Augue pharetra sem ullamcorper nisl ante. Ac arcu donec sed nunc pharetra nunc vitae. Volutpat arcu augue ut quisque id ut. A et viverra at nunc nisl. Ac a amet ullamcorper nulla etiam suspendisse. Montes tincidunt adipiscing commodo porttitor sit quis dolor velit quam.Commodo mauris semper mauris vitae mauris ultrices. Risus velit aliquet ultrices phasellus id. Duis ut magna rutrum purus ridiculus. Sed condimentum leo.At ac aliquam morbi nullam lorem neque dignissim egestas.',
        name_1: 'Korporativ sayt',
        content_1: 'Korporativ sayt - Sizin şirkətin internetdə olan təmsilçisidir. Doğru şəkildə hazırlanmış korporativ sayt şirkətin üstünlüklərini, müsbət imicini və gücünü özündə əks etdirə bilər.',
        name_2: 'Landing Page Dizaynı',
        content_2: 'Düzgün şəkildə qurulmuş bir səhifəlik landing page hər hansı bir məhsul və ya xidmətinizin satışına necə müsbət təsir etməsini təsəvvür edin.',
        name_3: 'Adaptiv Dizayn',
        content_3: 'Dünyada internet istifadəçilərinin 95% saytlara mobil telefon vasitəsilə daxil olduğunu nəzərə alaraq, təmsil etdiyiniz şirkətin saytının adaptiv olması mütləqdir.',
    },

    {
        id:'3',
        title: 'İnkişaf',
        info: 'Augue pharetra sem ullamcorper nisl ante. Ac arcu donec sed nunc pharetra nunc vitae. Volutpat arcu augue ut quisque id ut. A et viverra at nunc nisl. Ac a amet ullamcorper nulla etiam suspendisse. Montes tincidunt adipiscing commodo porttitor sit quis dolor velit quam.Commodo mauris semper mauris vitae mauris ultrices. Risus velit aliquet ultrices phasellus id. Duis ut magna rutrum purus ridiculus. Sed condimentum leo.At ac aliquam morbi nullam lorem neque dignissim egestas.',
        name_1: 'Korporativ sayt',
        content_1: 'Korporativ sayt - Sizin şirkətin internetdə olan təmsilçisidir. Doğru şəkildə hazırlanmış korporativ sayt şirkətin üstünlüklərini, müsbət imicini və gücünü özündə əks etdirə bilər.',
        name_2: 'Landing Page Dizaynı',
        content_2: 'Düzgün şəkildə qurulmuş bir səhifəlik landing page hər hansı bir məhsul və ya xidmətinizin satışına necə müsbət təsir etməsini təsəvvür edin.',
        name_3: 'Adaptiv Dizayn',
        content_3: 'Dünyada internet istifadəçilərinin 95% saytlara mobil telefon vasitəsilə daxil olduğunu nəzərə alaraq, təmsil etdiyiniz şirkətin saytının adaptiv olması mütləqdir.',
    },

    {
        id:'4',
        title: 'Brendləşmə',
        info: 'Augue pharetra sem ullamcorper nisl ante. Ac arcu donec sed nunc pharetra nunc vitae. Volutpat arcu augue ut quisque id ut. A et viverra at nunc nisl. Ac a amet ullamcorper nulla etiam suspendisse. Montes tincidunt adipiscing commodo porttitor sit quis dolor velit quam.Commodo mauris semper mauris vitae mauris ultrices. Risus velit aliquet ultrices phasellus id. Duis ut magna rutrum purus ridiculus. Sed condimentum leo.At ac aliquam morbi nullam lorem neque dignissim egestas.',
        name_1: 'Korporativ sayt',
        content_1: 'Korporativ sayt - Sizin şirkətin internetdə olan təmsilçisidir. Doğru şəkildə hazırlanmış korporativ sayt şirkətin üstünlüklərini, müsbət imicini və gücünü özündə əks etdirə bilər.',
        name_2: 'Landing Page Dizaynı',
        content_2: 'Düzgün şəkildə qurulmuş bir səhifəlik landing page hər hansı bir məhsul və ya xidmətinizin satışına necə müsbət təsir etməsini təsəvvür edin.',
        name_3: 'Adaptiv Dizayn',
        content_3: 'Dünyada internet istifadəçilərinin 95% saytlara mobil telefon vasitəsilə daxil olduğunu nəzərə alaraq, təmsil etdiyiniz şirkətin saytının adaptiv olması mütləqdir.',
    },

    {
        id:'5',
        title: 'Mobil Proqram',
        info: 'Augue pharetra sem ullamcorper nisl ante. Ac arcu donec sed nunc pharetra nunc vitae. Volutpat arcu augue ut quisque id ut. A et viverra at nunc nisl. Ac a amet ullamcorper nulla etiam suspendisse. Montes tincidunt adipiscing commodo porttitor sit quis dolor velit quam.Commodo mauris semper mauris vitae mauris ultrices. Risus velit aliquet ultrices phasellus id. Duis ut magna rutrum purus ridiculus. Sed condimentum leo.At ac aliquam morbi nullam lorem neque dignissim egestas.',
        name_1: 'Korporativ sayt',
        content_1: 'Korporativ sayt - Sizin şirkətin internetdə olan təmsilçisidir. Doğru şəkildə hazırlanmış korporativ sayt şirkətin üstünlüklərini, müsbət imicini və gücünü özündə əks etdirə bilər.',
        name_2: 'Landing Page Dizaynı',
        content_2: 'Düzgün şəkildə qurulmuş bir səhifəlik landing page hər hansı bir məhsul və ya xidmətinizin satışına necə müsbət təsir etməsini təsəvvür edin.',
        name_3: 'Adaptiv Dizayn',
        content_3: 'Dünyada internet istifadəçilərinin 95% saytlara mobil telefon vasitəsilə daxil olduğunu nəzərə alaraq, təmsil etdiyiniz şirkətin saytının adaptiv olması mütləqdir.',
    },

    {
        id:'6',
        title: 'İllüstrasiyalar',
        info: 'Augue pharetra sem ullamcorper nisl ante. Ac arcu donec sed nunc pharetra nunc vitae. Volutpat arcu augue ut quisque id ut. A et viverra at nunc nisl. Ac a amet ullamcorper nulla etiam suspendisse. Montes tincidunt adipiscing commodo porttitor sit quis dolor velit quam.Commodo mauris semper mauris vitae mauris ultrices. Risus velit aliquet ultrices phasellus id. Duis ut magna rutrum purus ridiculus. Sed condimentum leo.At ac aliquam morbi nullam lorem neque dignissim egestas.',
        name_1: 'Korporativ sayt',
        content_1: 'Korporativ sayt - Sizin şirkətin internetdə olan təmsilçisidir. Doğru şəkildə hazırlanmış korporativ sayt şirkətin üstünlüklərini, müsbət imicini və gücünü özündə əks etdirə bilər.',
        name_2: 'Landing Page Dizaynı',
        content_2: 'Düzgün şəkildə qurulmuş bir səhifəlik landing page hər hansı bir məhsul və ya xidmətinizin satışına necə müsbət təsir etməsini təsəvvür edin.',
        name_3: 'Adaptiv Dizayn',
        content_3: 'Dünyada internet istifadəçilərinin 95% saytlara mobil telefon vasitəsilə daxil olduğunu nəzərə alaraq, təmsil etdiyiniz şirkətin saytının adaptiv olması mütləqdir.',
    },
    {
        id:'7',
        title: 'Proqram Dizaynı',
        info: 'Augue pharetra sem ullamcorper nisl ante. Ac arcu donec sed nunc pharetra nunc vitae. Volutpat arcu augue ut quisque id ut. A et viverra at nunc nisl. Ac a amet ullamcorper nulla etiam suspendisse. Montes tincidunt adipiscing commodo porttitor sit quis dolor velit quam.Commodo mauris semper mauris vitae mauris ultrices. Risus velit aliquet ultrices phasellus id. Duis ut magna rutrum purus ridiculus. Sed condimentum leo.At ac aliquam morbi nullam lorem neque dignissim egestas.',
        name_1: 'Korporativ sayt',
        content_1: 'Korporativ sayt - Sizin şirkətin internetdə olan təmsilçisidir. Doğru şəkildə hazırlanmış korporativ sayt şirkətin üstünlüklərini, müsbət imicini və gücünü özündə əks etdirə bilər.',
        name_2: 'Landing Page Dizaynı',
        content_2: 'Düzgün şəkildə qurulmuş bir səhifəlik landing page hər hansı bir məhsul və ya xidmətinizin satışına necə müsbət təsir etməsini təsəvvür edin.',
        name_3: 'Adaptiv Dizayn',
        content_3: 'Dünyada internet istifadəçilərinin 95% saytlara mobil telefon vasitəsilə daxil olduğunu nəzərə alaraq, təmsil etdiyiniz şirkətin saytının adaptiv olması mütləqdir.',
    },
    {
        id:'8',
        title: 'Şəkil',
        info: 'Augue pharetra sem ullamcorper nisl ante. Ac arcu donec sed nunc pharetra nunc vitae. Volutpat arcu augue ut quisque id ut. A et viverra at nunc nisl. Ac a amet ullamcorper nulla etiam suspendisse. Montes tincidunt adipiscing commodo porttitor sit quis dolor velit quam.Commodo mauris semper mauris vitae mauris ultrices. Risus velit aliquet ultrices phasellus id. Duis ut magna rutrum purus ridiculus. Sed condimentum leo.At ac aliquam morbi nullam lorem neque dignissim egestas.',
        name_1: 'Korporativ sayt',
        content_1: 'Korporativ sayt - Sizin şirkətin internetdə olan təmsilçisidir. Doğru şəkildə hazırlanmış korporativ sayt şirkətin üstünlüklərini, müsbət imicini və gücünü özündə əks etdirə bilər.',
        name_2: 'Landing Page Dizaynı',
        content_2: 'Düzgün şəkildə qurulmuş bir səhifəlik landing page hər hansı bir məhsul və ya xidmətinizin satışına necə müsbət təsir etməsini təsəvvür edin.',
        name_3: 'Adaptiv Dizayn',
        content_3: 'Dünyada internet istifadəçilərinin 95% saytlara mobil telefon vasitəsilə daxil olduğunu nəzərə alaraq, təmsil etdiyiniz şirkətin saytının adaptiv olması mütləqdir.',
    }
]